//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoprevoznikGUI.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoprevoznikDBEntities : DbContext
    {
        public AutoprevoznikDBEntities()
            : base("name=AutoprevoznikDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autobu> Autobus { get; set; }
        public virtual DbSet<Garaza> Garazas { get; set; }
        public virtual DbSet<Karta> Kartas { get; set; }
        public virtual DbSet<Kondukter> Kondukters { get; set; }
        public virtual DbSet<Kontroler> Kontrolers { get; set; }
        public virtual DbSet<Linija> Linijas { get; set; }
        public virtual DbSet<Naselje> Naseljes { get; set; }
        public virtual DbSet<Putnik> Putniks { get; set; }
        public virtual DbSet<Putuje> Putujes { get; set; }
        public virtual DbSet<Radnik> Radniks { get; set; }
        public virtual DbSet<Stanica> Stanicas { get; set; }
        public virtual DbSet<Vozac> Vozacs { get; set; }
    }
}
