//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoprevoznikGUI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Karta()
        {
            this.Kondukters = new HashSet<Kondukter>();
            this.Kontrolers = new HashSet<Kontroler>();
        }
    
        public Nullable<int> sediste { get; set; }
        public Nullable<System.DateTime> datum_kup { get; set; }
        public Nullable<decimal> cena { get; set; }
        public string relacija { get; set; }
        public int Putnik_mbr_p { get; set; }
        public int Putuje_Autobus_reg { get; set; }
        public int Putuje_Linija_br_linije { get; set; }
        public System.DateTime Putuje_dv_polaska { get; set; }
    
        public virtual Putnik Putnik { get; set; }
        public virtual Putuje Putuje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kondukter> Kondukters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontroler> Kontrolers { get; set; }
    }
}
