//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoprevoznikGUI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Putuje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Putuje()
        {
            this.Kartas = new HashSet<Karta>();
        }
    
        public int Autobus_reg { get; set; }
        public int Linija_br_linije { get; set; }
        public System.DateTime dv_polaska { get; set; }
        public Nullable<System.DateTime> dv_dolaska { get; set; }
    
        public virtual Autobu Autobu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Karta> Kartas { get; set; }
        public virtual Linija Linija { get; set; }
    }
}
