//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoprevoznikGUI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radnik
    {
        public int mbr_r { get; set; }
        public string ime_r { get; set; }
        public string prz_r { get; set; }
        public Nullable<System.DateTime> god_r { get; set; }
        public string adresa { get; set; }
        public Nullable<int> br_tel { get; set; }
        public System.DateTime ugovor_sklopljen { get; set; }
        public Nullable<System.DateTime> ugovor_istekao { get; set; }
    
        public virtual Kondukter Kondukter { get; set; }
        public virtual Kontroler Kontroler { get; set; }
        public virtual Vozac Vozac { get; set; }
    }
}
